algorithm: push_relabel_mincut
runs:
  num_runs: 1
  hp_space: pr_mc_one
  batch_size: 32
  early_stop: true
  early_stop_patience: 20
  train_steps: 20000
  verbose: true
  log_every: 100
experiment:
  name: pr-mc
  higher_is_better: false
  num_valid_trials: 1

